version: '3.6'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle_cache:/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:10.4-alpine
volumes:
  bundle_cache:
